# syntax=docker/dockerfile:1

FROM alpine
ARG TARGETARCH
RUN apk add --no-cache tzdata nano ca-certificates && update-ca-certificates
WORKDIR /
COPY bin/npc-${TARGETARCH} /npc
RUN chmod +x /npc
VOLUME /conf
ENTRYPOINT ["/npc"]
